server {
    listen 80;
    server_name 10.65.10.22;

    root /usr/share/nginx/html;
    index index.html;

    # Все запросы к фронту (например, /about, /dashboard и т.д.)
    location / {
        try_files $uri /index.html;
    }

    # Проксирование API-запросов к бэкенду
    location /api/ {
        proxy_pass http://10.65.10.22:5110;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # (Необязательно) Если у тебя картинки или файлы с бэка по пути /uploads/
    location /uploads/ {
        proxy_pass http://10.65.10.22:5110;
    }
}
